server:
  port: 65534
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-connections: 10000
    acceptCount: 2000
    threads:
      max: 1000
      min-spare: 20
    max-http-form-post-size: 200MB
spring:
  profiles:
    active: "@profiles.active@"
  application:
    name: SmartSports-springboot
  main:
    allow-bean-definition-overriding: true
  mvc:
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
    pathmatch:
      matching-strategy: ant_path_matcher
#    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 200MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh
    time-zone: GMT+8
    default-property-inclusion: non_null
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

