package com.henu.competition.model;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

import com.henu.competition.common.model.BaseBean;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

import com.henu.competition.common.model.OverrideBeanMethods;

/**
 * project_info
 *
 * @author Yalu Wang
 * @version 1.0.0 2023-11-13
 */
@Setter
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
@ApiModel(description = "project_info")
@TableName("project_info")
public class ProjectInfo extends BaseBean {
    /** 版本号 */
    private static final long serialVersionUID = -8619267124516428743L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /**  */
    @ApiModelProperty(value = "", position = 1)
    @JsonProperty(index = 1)
    @TableId
    private String id;

    /** 选题名称 */
    @ApiModelProperty(value = "选题名称", position = 2)
    @JsonProperty(index = 2)
    @NotBlank(message = "选题名称不能为空！")
    private String name;

    /** 选题分组。1：工程应用组，2：人工智能组 */
    @ApiModelProperty(value = "选题分组。1：工程应用组，2：人工智能组", position = 3)
    @JsonProperty(index = 3)
    @NotNull(message = "选题分组不能为空！")
    private Integer sectionalization;

    /* This code was generated by TableGo tools, mark 1 end. */
}