package com.henu.competition.model;

import javax.validation.constraints.NotBlank;

import com.henu.competition.common.model.BaseBean;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

import com.henu.competition.common.model.OverrideBeanMethods;

/**
 * school_info
 *
 * @author Yalu Wang
 * @version 1.0.0 2023-11-09
 */
@Setter
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
@ApiModel(description = "school_info")
@TableName("school_info")
public class SchoolInfo extends BaseBean {
    /** 版本号 */
    private static final long serialVersionUID = -1735853125647990489L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /**  */
    @ApiModelProperty(value = "", position = 1)
    @JsonProperty(index = 1)
    @TableId
    private String id;

    /** 学校代码 */
    @ApiModelProperty(value = "学校代码", position = 2)
    @JsonProperty(index = 2)
    @NotBlank(message = "学校代码不能为空！")
    private String code;

    /** 学校名称 */
    @ApiModelProperty(value = "学校名称", position = 3)
    @JsonProperty(index = 3)
    @NotBlank(message = "学校名称不能为空！")
    private String name;

    /* This code was generated by TableGo tools, mark 1 end. */
}