package com.henu.competition.model;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

import com.henu.competition.common.model.BaseBean;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

import com.henu.competition.common.model.OverrideBeanMethods;

/**
 * squadron_user_map
 *
 * @author Yalu Wang
 * @version 1.0.0 2023-11-09
 */
@Setter
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
@ApiModel(description = "squadron_user_map")
@TableName("squadron_user_map")
public class SquadronUserMap extends BaseBean {
    /** 版本号 */
    private static final long serialVersionUID = 7920762467651703134L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /**  */
    @ApiModelProperty(value = "", position = 1)
    @JsonProperty(index = 1)
    @TableId
    private String id;

    /** 用户id */
    @ApiModelProperty(value = "用户id", position = 2)
    @JsonProperty(index = 2)
    @NotBlank(message = "用户id不能为空！")
    private String userId;

    /** 战队id */
    @ApiModelProperty(value = "战队id", position = 3)
    @JsonProperty(index = 3)
    @NotBlank(message = "战队id不能为空！")
    private String squadronId;

    /**  */
    @ApiModelProperty(value = "", position = 4)
    @JsonProperty(index = 4)
    @NotNull(message = "leaderTag不能为空！")
    private Integer leaderTag;

    /* This code was generated by TableGo tools, mark 1 end. */
}