package com.henu.competition.model;

import javax.validation.constraints.NotBlank;

import com.henu.competition.common.model.BaseBean;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

import com.henu.competition.common.model.OverrideBeanMethods;

/**
 * system_Setting
 *
 * @author Yalu Wang
 * @version 1.0.0 2023-11-21
 */
@Setter
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
@ApiModel(description = "system_Setting")
@TableName("system_Setting")
public class SystemSetting extends BaseBean {
    /** 版本号 */
    private static final long serialVersionUID = -4255367834850160643L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /**  */
    @ApiModelProperty(value = "", position = 1)
    @JsonProperty(index = 1)
    @TableId
    private String id;

    /** 名称 */
    @ApiModelProperty(value = "名称", position = 2)
    @JsonProperty(index = 2)
    @NotBlank(message = "名称不能为空！")
    private String name;

    /** 值 */
    @ApiModelProperty(value = "值", position = 3)
    @JsonProperty(index = 3)
    @NotBlank(message = "值不能为空！")
    private String value;

    /** 备注 */
    @ApiModelProperty(value = "备注", position = 4)
    @JsonProperty(index = 4)
    @NotBlank(message = "备注不能为空！")
    private String remark;

    /* This code was generated by TableGo tools, mark 1 end. */
}