package com.henu.competition.model;

import javax.validation.constraints.NotBlank;

import com.henu.competition.common.model.BaseBean;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

import com.henu.competition.common.model.OverrideBeanMethods;

/**
 * user
 *
 * @author Yalu Wang
 * @version 1.0.0 2023-11-09
 */
@Setter
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
@ApiModel(description = "user")
@TableName("user")
public class User extends BaseBean {
    /** 版本号 */
    private static final long serialVersionUID = 4292295679076131000L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /**  */
    @ApiModelProperty(value = "", position = 1)
    @JsonProperty(index = 1)
    @TableId
    private String id;

    /** 用户名 */
    @ApiModelProperty(value = "用户名", position = 2)
    @JsonProperty(index = 2)
    @NotBlank(message = "用户名不能为空！")
    private String name;

    /** 密码 */
    @ApiModelProperty(value = "密码", position = 3)
    @JsonProperty(index = 3)
    @NotBlank(message = "密码不能为空！")
    private String password;

    /** 真实名称 */
    @ApiModelProperty(value = "真实名称", position = 4)
    @JsonProperty(index = 4)
    private String realName;

    /** 性别。1：男，2：女 */
    @ApiModelProperty(value = "学历。1：博士研究生，2：硕士研究生，3：本科，4：专科", position = 14)
    @JsonProperty(index = 14)
    private String education;

    /** 性别。1：男，2：女 */
    @ApiModelProperty(value = "性别。1：男，2：女", position = 5)
    @JsonProperty(index = 5)
    private String sex;

    /** 民族 */
    @ApiModelProperty(value = "民族", position = 6)
    @JsonProperty(index = 6)
    private String nation;

    /** 电话 */
    @ApiModelProperty(value = "电话", position = 7)
    @JsonProperty(index = 7)
    private String phone;

    /** 邮箱 */
    @ApiModelProperty(value = "邮箱", position = 8)
    @JsonProperty(index = 8)
    private String email;

    /** 学号 */
    @ApiModelProperty(value = "学号", position = 9)
    @JsonProperty(index = 9)
    private String sNumber;

    /** 学校id */
    @ApiModelProperty(value = "学校id", position = 10)
    @JsonProperty(index = 10)
    @NotBlank(message = "学校id不能为空！")
    private String schoolId;

    /** 地址 */
    @ApiModelProperty(value = "地址", position = 11)
    @JsonProperty(index = 11)
    private String address;

    /** 学生证图片 */
    @ApiModelProperty(value = "学生证图片", position = 12)
    @JsonProperty(index = 12)
    private String sicImage;

    /** 备注 */
    @ApiModelProperty(value = "备注", position = 13)
    @JsonProperty(index = 13)
    private String remark;

    /* This code was generated by TableGo tools, mark 1 end. */
}