package com.henu.competition.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.*;
import lombok.experimental.Accessors;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.sql.Timestamp;

/**
 * user
 *
 * @author Yalu Wang
 * @version 1.0.0 2023-08-02
 */
@Setter
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
@ApiModel(description = "user")
public class User  {
    /** 版本号 */
    private static final long serialVersionUID = 6260124840864794503L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /**  */
    @ApiModelProperty(value = "", position = 1)
    @JsonProperty(index = 1)
    private String id;

    /** 用户名 */
    @ApiModelProperty(value = "用户名", position = 2)
    @JsonProperty(index = 2)
    @NotBlank(message = "用户名不能为空！")
    private String name;

    /** 昵称 */
    @ApiModelProperty(value = "昵称", position = 2)
    @JsonProperty(index = 2)
    @NotBlank(message = "昵称不能为空！")
    private String nickname;

    /** 密码 */
    @ApiModelProperty(value = "密码", position = 3)
    @JsonProperty(index = 3)
    @NotBlank(message = "密码不能为空！")
    private String password;

    /** 密码 */
    @ApiModelProperty(value = "token", position = 3)
    @JsonProperty(index = 3)
    @NotBlank(message = "密码不能为空！")
    private String token;

    /** 签名 */
    @ApiModelProperty(value = "签名", position = 4)
    @JsonProperty(index = 4)
    private String signature;

    /** 性别 */
    @ApiModelProperty(value = "性别，0男，1女", position = 5)
    @JsonProperty(index = 5)
    private Integer sex;

    /** 生日 */
    @ApiModelProperty(value = "生日", position = 6)
    @JsonProperty(index = 6)
//    @JsonFormat(timezone = "GMT+8", pattern = DatePattern.NORM_DATE_PATTERN)
    private Timestamp birthday;

    /** 照片（头像） */
    @ApiModelProperty(value = "照片（头像）", position = 7)
    @JsonProperty(index = 7)
    private String photo;

    /** 照片（头像） */
    @ApiModelProperty(value = "用户类型，0：系统管理，1：普通用户，2：后端用户", position = 7)
    @JsonProperty(index = 7)
    private Integer userType;

    /** 可用状态，0不可用，1正常 */
    @ApiModelProperty(value = "可用状态，0不可用，1正常", position = 8)
    @JsonProperty(index = 8)
    @NotNull(message = "可用状态不能为空！")
    private Integer status;

    /* This code was generated by TableGo tools, mark 1 end. */
}