package com.henu.competition.pojo.req;

import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.henu.competition.common.model.BaseBean;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.*;
import lombok.experimental.Accessors;
import org.hibernate.validator.constraints.Length;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

/**
 * squadron
 *
 * @author Yalu Wang
 * @version 1.0.0 2023-11-09
 */
@Setter
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
@ApiModel(description = "CreatSquadronReq")
public class CreatSquadronReq{
    /** 版本号 */
    private static final long serialVersionUID = -2971888522404031760L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /**  */
    @ApiModelProperty(value = "", position = 1)
    @JsonProperty(index = 1)
    private String id;

    /** 战队名称 */
    @ApiModelProperty(value = "战队名称", position = 2)
    @JsonProperty(index = 2)
    @NotBlank(message = "战队名称不能为空！")
    @Length(min = 2,max = 12)
    private String name;

    /** 创建人id */
    @ApiModelProperty(value = "选题id", position = 3)
    @JsonProperty(index = 3)
    @NotBlank(message = "选题id不能为空！")
    private String projectId;

    /* This code was generated by TableGo tools, mark 1 end. */
}