package com.henu.competition.pojo.req;

import javax.validation.constraints.NotBlank;

import com.henu.competition.common.model.BaseBean;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

/**
 * user
 *
 * @author Yalu Wang
 * @version 1.0.0 2023-11-09
 */
@Setter
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
@ApiModel(description = "ModifyUserReq")
public class ModifyUserReq {
    /** 版本号 */
    private static final long serialVersionUID = 4292295679076131000L;


    /** 真实名称 */
    @ApiModelProperty(value = "真实名称", position = 4, required = true)
    @JsonProperty(index = 4)
    @NotBlank(message = "真实名称不能为空！")
    private String realName;

    /** 性别。1：男，2：女 */
    @ApiModelProperty(value = "性别。1：男，2：女", position = 5, required = true)
    @JsonProperty(index = 5)
    @NotBlank(message = "性别不能为空！")
    private String sex;

    /** 民族 */
    @ApiModelProperty(value = "民族", position = 6, required = true)
    @JsonProperty(index = 6)
    @NotBlank(message = "民族不能为空！")
    private String nation;

    /** 电话 */
    @ApiModelProperty(value = "电话", position = 7, required = true)
    @JsonProperty(index = 7)
    @NotBlank(message = "电话不能为空！")
    private String phone;

    /** 邮箱 */
    @ApiModelProperty(value = "邮箱", position = 8, required = true)
    @JsonProperty(index = 8)
    @NotBlank(message = "邮箱不能为空！")
    private String email;

    /** 学号 */
    @ApiModelProperty(value = "学号", position = 9, required = true)
    @JsonProperty(index = 9)
    @NotBlank(message = "学号不能为空！")
    private String sNumber;

    /** 学校id */
    @ApiModelProperty(value = "学校id", position = 10, required = true)
    @JsonProperty(index = 10)
    @NotBlank(message = "学校不能为空！")
    private String schoolId;

    /** 地址 */
    @ApiModelProperty(value = "地址", position = 11)
    @JsonProperty(index = 11)
    private String address;

    /** 学生证图片 */
    @ApiModelProperty(value = "学生证图片", position = 12, required = true)
    @JsonProperty(index = 12)
    @NotBlank(message = "学生证图片不能为空！")
    private String sicImage;

    /** 备注 */
    @ApiModelProperty(value = "备注", position = 13)
    @JsonProperty(index = 13)
    private String remark;

    /** 备注 */
    @ApiModelProperty(value = "学历", position = 14)
    @JsonProperty(index = 14)
    private String education;

    /* This code was generated by TableGo tools, mark 1 end. */
}