package com.henu.competition.pojo.req;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.*;
import lombok.experimental.Accessors;

import javax.validation.constraints.NotBlank;

/**
 * user
 *
 * @author Yalu Wang
 * @version 1.0.0 2023-11-09
 */
@Setter
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
@ApiModel(description = "ModifyCap")
public class ModifyCapReq {
    /** 版本号 */
    private static final long serialVersionUID = 4292295679076131000L;


    /** 真实名称 */
    @ApiModelProperty(value = "战队id", position = 1, required = true)
    @JsonProperty(index = 1)
    @NotBlank(message = "战队id不能为空！")
    private String squadronId;

    /** 性别。1：男，2：女 */
    @ApiModelProperty(value = "新队长用户id", position = 5, required = true)
    @JsonProperty(index = 5)
    @NotBlank(message = "新队长用户id不能为空！")
    private String newCapId;

    /* This code was generated by TableGo tools, mark 1 end. */
}