package com.henu.competition.pojo.req;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.*;
import lombok.experimental.Accessors;

import javax.validation.constraints.NotBlank;

/**
 * user
 *
 * @author Yalu Wang
 * @version 1.0.0 2023-08-02
 */
@Setter
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
@ApiModel(description = "UserSigUpReq")
public class UserSigUpReq {
    /** 版本号 */
    private static final long serialVersionUID = 6260124840864794503L;

    /* This code was generated by TableGo tools, mark 1 begin. */



    @ApiModelProperty(value = "用户名", position = 1,required = true)
    @JsonProperty(index = 1)
    @NotBlank(message = "用户名不能为空！")
    private String name;


    @ApiModelProperty(value = "密码", position = 2,required = true)
    @JsonProperty(index = 2)
    @NotBlank(message = "密码不能为空！")
    private String password;

    @ApiModelProperty(value = "学校", position = 3,required = true)
    @JsonProperty(index = 3)
    @NotBlank(message = "学校不能为空！")
    private String schoolId;

    @ApiModelProperty(value = "验证码", position = 4,required = true)
    @JsonProperty(index = 4)
    @NotBlank(message = "验证码不能为空！")
    private String code;



    /* This code was generated by TableGo tools, mark 1 end. */
}